export const states = [
    "Alabama",
    "Alaska",
    "Arizona",
    "Arkansas",
    "California",
    "Colorado",
    "Connecticut",
    "Delaware",
    "Florida",
    "Georgia",
    "Hawaii",
    "Idaho",
    "Illinois",
    "Indiana",
    "Iowa",
    "Kansas",
    "Kentucky",
    "Louisiana",
    "Maine",
    "Maryland",
    "Massachusetts",
    "Michigan",
    "Minnesota",
    "Mississippi",
    "Missouri",
    "Montana",
    "Nebraska",
    "Nevada",
    "New Hampshire",
    "New Jersey",
    "New Mexico",
    "New York",
    "North Carolina",
    "North Dakota",
    "Ohio",
    "Oklahoma",
    "Oregon",
    "Pennsylvania",
    "Rhode Island",
    "South Carolina",
    "South Dakota",
    "Tennessee",
    "Texas",
    "Utah",
    "Vermont",
    "Virginia",
    "Washington",
    "West Virginia",
    "Wisconsin",
    "Wyoming",
  ]

  export const departments = [
    "Sales",
    "Marketing",
    "Engineering",
    "Human Resources",
    "Legal",
  ]

  export const columns = [
    { field: "firstName", headerName: "First name", width:160},
    { field: "lastName", headerName: "Last name", width:160},
    { field: "startDate", headerName: "Start date", width:160},
    { field: "department", headerName: "Department", width:160},
    { field: "birthDate", headerName: "Birth Date", width:160},
    { field: "street", headerName: "Street", width:160},
    { field: "city", headerName: "City", width:160},
    { field: "state", headerName: "State", width:160},
    { field: "zipcode", headerName: "Zipcode", width:160},
  ]